FROM nginx:alpine AS builder

# Remove default nginx site
RUN rm -rf /usr/share/nginx/html/*

# Copy  app files
COPY . /usr/share/nginx/html


# Stage 2: Runtime

FROM nginx:alpine

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Remove default nginx site
RUN rm -rf /usr/share/nginx/html/*

# Copy built files from builder stage
COPY --from=builder /usr/share/nginx/html /usr/share/nginx/html

# Fix permissions
RUN chown -R appuser:appgroup /usr/share/nginx/html \
    && chown -R appuser:appgroup /var/cache/nginx \
    && chown -R appuser:appgroup /var/run

# Switch to non-root user
USER appuser

# Health check (nginx must return 200)
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -qO- http://localhost:80/ || exit 1

# Expose port
EXPOSE 80
