apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MohamedA15/Eks-project.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: eks-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true